name: Quote Action
description: A GitHub Action to dynamically add inspirational quotes to your GitHub profile
author: oseveen

branding:
  icon: book-open
  color: black

inputs:
  typeQuote:
    required: false
    description: Type of quote
    default: Random

  pathQuote:
    required: false
    description: path to markdown
    default: ./readme.md
  
  commitMessage:
    required: false
    description: Commit message that will be used
    default: 📖 Updating quote in markdown file

runs:
  using: composite

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: npm install
    
    - name: Run quote script
      shell: bash
      run: npx tsx ${{ github.action_path }}/source/index.ts
      env:
        INPUT_TYPEQUOTE: ${{ inputs.typeQuote }}
        INPUT_PATHQUOTE: ${{ inputs.pathQuote }}
        INPUT_COMMITMESSAGE: ${{ inputs.commitMessage }}